---
title: "Data Cleaning"
author: "Chase Mayfield"
date: "`r Sys.Date()`"
output: pdf_document



```{r setup, include=FALSE}
library(data.table)
library("readxl")
library(ggplot2)
```

```{r}
df<-fread("C:/Users/15307/OneDrive/Desktop/math485/export.txt")

```

```{r}
names(df)
```


```{r, include=FALSE}
table(df$`AFP Post-Orchiectomy Lab Value Recode (2010+)`)
factor(df$`hCG Post-Orchiectomy Range Recode (2010+)`,labels=c("5,000-50,000", "Above normal and less than 5,000 MIU/mL", "Blank(s)", "Greater than 50,000" , "Blank(s)", "Blank(s)", "Blank(s)", "normal"))
```

```{r}
table(df$`AFP Post-Orchiectomy Lab Value Recode (2010+)`)

```


```{r}
table(df$`Surgery of oth reg/dis sites (1998-2002)`)
table(df$`Scope of reg lymph nd surg (1998-2002)`)
```



```{r}
table(df$`Chemotherapy recode (yes, no/unk)`)
table(df$`Radiation recode`)
table(df$`Reason no cancer-directed surgery`)
```


```{r}
unique(df$`Primary Site`)
```


```{r}
ex_data <- read_excel("C:/Users/15307/Downloads/testis.xlsx")
```

```{r}
names(ex_data)[names(ex_data) == "CS Tumor Size/Ext Eval (2004-2015)"] <- "tumor_size"
```

```{r}
ex_data$tumor_size = as.numeric(ex_data$tumor_size)
ex_data[ex_data =="Blank(s)"] <- NA

```


```{r}
unique(ex_data$tumor_size)
summary(ex_data$tumor_size, na.rm = TRUE)
sd(ex_data$tumor_size, na.rm = TRUE)
```

```{r}
ggplot(data = ex_data, aes(x = tumor_size))+
  geom_histogram(fill="blue",color="white")+
  labs(x='Tumor Size', y='Frequency', title = 'Tumor Size Histogram')
```

